[theme]
primaryColor = "#8B5CF6"
backgroundColor = "#2D1B69"
secondaryBackgroundColor = "#4C1D95"
textColor = "#E0E7FF"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false
